// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAn0ddi9wefMr9qJF15x4eE7Z-1f-K6Qw',
    appId: '1:1014798930960:android:f587c987f060c4beee2695',
    messagingSenderId: '1014798930960',
    projectId: 'todo-app-99643',
    databaseURL: 'https://todo-app-99643-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-99643.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsO4cRmnCw5kjsN5valryldyu3viVka3o',
    appId: '1:1014798930960:ios:8b18752afa1eaa2bee2695',
    messagingSenderId: '1014798930960',
    projectId: 'todo-app-99643',
    databaseURL: 'https://todo-app-99643-default-rtdb.firebaseio.com',
    storageBucket: 'todo-app-99643.appspot.com',
    androidClientId: '1014798930960-32mh1l030gn6sak5qq412f4j915ntk4o.apps.googleusercontent.com',
    iosClientId: '1014798930960-33dltr0vj0cij8hu0n4552jk59atb861.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
